# Generated by Django 3.1.2 on 2020-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('information', models.TextField()),
                ('information2', models.TextField()),
                ('introduction', models.TextField()),
            ],
        ),
    ]
