# Generated by Django 3.1.2 on 2020-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_film_comment_app', '0002_film_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('film_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
